application: sprocket-io
version: 1
runtime: go
api_version: go1

handlers:
- url: /third_party
  static_dir: third_party

- url: /themes
  static_dir: themes

- url: /admin/.*
  script: _go_app
  login: admin
  auth_fail_action: redirect

- url: /.*
  script: _go_app

